//
// Created by p_svengong on 2021/1/18.
//

#ifndef RIRU_MODULETEMPLATE_MASTERV23_FRIDA_GUMJS_EXAMPLE_H
#define RIRU_MODULETEMPLATE_MASTERV23_FRIDA_GUMJS_EXAMPLE_H

#endif //RIRU_MODULETEMPLATE_MASTERV23_FRIDA_GUMJS_EXAMPLE_H
int gumjsHook();